### ISSUE TITLE
[GYM 104]: Exam question 12 is broken

### ISSUE THREAD

**Issue by rediris** [gymnasium/tracker#233]
I think there's something wonky happening with question 12:
<img width="1022" alt="Screen Shot 2022-03-11 at 10 42 43 AM" src="https://user-images.githubusercontent.com/1010395/157900074-f7e377e4-4e9c-458d-b9cc-29d1ef46c1a4.png">

Direct link: https://thegymnasium.com/courses/GYM/104/0/courseware/d23fc174f83d49de92bb0263e5c906b8/ec2b6199aa764e0695b054ec6210b4e6/

## To-Dos
- [x] Update final exam in Studio on staging/production
- [x] Update Lesson 4: Quiz in Studio on staging/production
- [x] Double-check and update quizzes in Studio on staging/production
- [x] Sync updates with https://github.com/gymnasium/studio-GYM-104

**Comment by jgagne** [comment]
@rediris Broken final exam question fixed in Studio on staging/production. I added to-do list — other tasks are in progress.
